GET http://localhost:3000
###
GET http://localhost:3000/abc
###
POST http://localhost:3000/user/register
Content-Type: application/json

{
  "email": "phaptran111@gmail.com",
  "password": "123456"
}
###
POST http://localhost:3000/user/refresh-token
###
POST http://localhost:3000/user/login
###
POST http://localhost:3000/user/logout
